/**
 * scripts/split-i18n.mjs — one-shot migration generator (v1.60.0, I18N-SPLIT).
 *
 * Reads the legacy monolithic key-major dictionary (the pre-split
 * `window.__I18N_DICT` object) from a captured source file and emits the
 * locale-major split layout the project moved to:
 *
 *   public/js/lib/locales/i18n-dict.<lang>.js   → window.__I18N_DICT_<LANG>
 *   public/js/lib/locales/i18n-dict.aliases.js  → window.__I18N_ALIASES
 *   tests/fixtures/i18n-dict.snapshot.json       → equality safety net
 *
 * After the split the per-locale files are the SOURCE OF TRUTH; this
 * script is kept only as a record of how the one-time migration was done
 * (and to regenerate the snapshot if the legacy file is reconstructed).
 *
 * Usage:  node scripts/split-i18n.mjs <path-to-legacy-i18n-dict.js>
 *
 * Keys are emitted single-quoted (so the `DICT.includes("'key'")`
 * text-scanner tests keep matching); values via JSON.stringify so any
 * quote/backslash/control char is escaped safely. Native non-ASCII
 * (대시보드, ダッシュボード, …) is preserved verbatim.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import vm from 'node:vm';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const LOCALES_DIR = resolve(ROOT, 'public', 'js', 'lib', 'locales');

// Insertion order matters: en first (it is the fallback + the file the
// "does key K exist" text-scanner tests read).
const LANGS = ['en', 'es', 'pt-BR', 'ko', 'ja', 'ru', 'zh-CN', 'zh-TW'];
const VARNAME = (lang) => `__I18N_DICT_${lang.toUpperCase().replace(/[^A-Z0-9]/g, '_')}`;

function loadLegacyDict(srcPath) {
  const src = readFileSync(srcPath, 'utf8');
  const sandbox = { window: {} };
  vm.createContext(sandbox);
  vm.runInContext(src, sandbox, { filename: 'legacy-i18n-dict.js' });
  if (!sandbox.window.__I18N_DICT) throw new Error(`no __I18N_DICT in ${srcPath}`);
  return sandbox.window.__I18N_DICT;
}

function quoteKey(k) {
  // Keys are dotted identifiers with no apostrophes; single-quote them so
  // the legacy `includes("'key'")` scanners keep matching. Guard anyway.
  return k.includes("'") || k.includes('\\') ? JSON.stringify(k) : `'${k}'`;
}

function header(lang) {
  return `/* global window */\n/**\n * ${lang} locale table for window.I18n — generated by the I18N-SPLIT\n * migration (v1.60.0). One file per locale so translators edit a single\n * language in isolation. Assembled into window.__I18N_DICT by\n * i18n-dict.js (loaded after every locale file). Keep key parity with the\n * other locales — tests/i18n-locale-files.test.mjs enforces it.\n *\n * Structured-data fixture: exempt from the 400-LOC file-size rule.\n */\nwindow.${VARNAME(lang)} = {\n`;
}

function main() {
  const srcArg = process.argv[2];
  if (!srcArg) { console.error('usage: node scripts/split-i18n.mjs <legacy-i18n-dict.js>'); process.exit(1); }
  const dict = loadLegacyDict(resolve(process.cwd(), srcArg));
  const keys = Object.keys(dict); // preserves original insertion order

  // 1. snapshot (equality safety net)
  writeFileSync(
    resolve(ROOT, 'tests', 'fixtures', 'i18n-dict.snapshot.json'),
    JSON.stringify(dict, null, 2) + '\n',
  );

  // 2. aliases file
  const aliasKeys = keys.filter((k) => dict[k] && dict[k]['@alias']);
  const aliasBody = aliasKeys.map((k) => `  ${quoteKey(k)}: ${JSON.stringify(dict[k]['@alias'])},`).join('\n');
  writeFileSync(
    resolve(LOCALES_DIR, 'i18n-dict.aliases.js'),
    `/* global window */\n/**\n * Language-independent alias map for window.I18n (I18N-SPLIT v1.60.0).\n * \`key: 'canonical.key'\` — i18n-dict.js rewrites each into\n * { '@alias': 'canonical.key' }. Aliases collapse duplicate-CONCEPT keys\n * (sidebar label = page title = dashboard tile) onto ONE translated\n * string; alias targets must exist and must not themselves be aliases\n * (enforced by tools/i18n-audit.mjs + tests).\n */\nwindow.__I18N_ALIASES = {\n${aliasBody}\n};\n`,
  );

  // 3. per-locale files
  const nonAliasKeys = keys.filter((k) => !(dict[k] && dict[k]['@alias']));
  for (const lang of LANGS) {
    const lines = [];
    for (const k of nonAliasKeys) {
      const v = dict[k][lang];
      if (v === undefined) continue; // parity is enforced elsewhere; skip gaps
      lines.push(`  ${quoteKey(k)}: ${JSON.stringify(v)},`);
    }
    writeFileSync(
      resolve(LOCALES_DIR, `i18n-dict.${lang}.js`),
      header(lang) + lines.join('\n') + '\n};\n',
    );
  }

  console.log(`split complete: ${nonAliasKeys.length} keys × ${LANGS.length} locales, ${aliasKeys.length} aliases`);
}

main();
